### ISSUE TITLE
Problem with tsc into es5

### ISSUE THREAD

**Issue by nofx3000** [sequelize/sequelize-typescript#1560]
# Issue
Hi, recently i build a koa2 app with sequelize-typscript, it worked perfectly when use ts-node to run the app, but when i tried to use command **tsc** to translate ts code into js es5 and run,  i found when it conducted some model query, findAll for example,  there was an error said "TypeError: Cannot read properties of undefined (reading 'findAll')". Beside, model synchronization cannot work either.
I'm not sure if it is because of the sequelize-typescript models cannot be imported correctly for some reason . 
Can you help me? Thanks.

## Versions

- sequelize: 6.28.0
- sequelize-typescript: 2.1.5
- typescript: 4.9.4

## Issue type

- [x] bug report
- [ ] feature request

## Actual behavior

  <-- GET /api/people/
----- TypeError: Cannot read properties of undefined (reading 'findAll')
    at DivisionService.<anonymous> (/Users/dh/Documents/vacation-system-server/dist/src/service/DivisionService.js:22:34)
    at Generator.next (<anonymous>)
    at /Users/dh/Documents/vacation-system-server/dist/src/service/DivisionService.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/dh/Documents/vacation-system-server/dist/src/service/DivisionService.js:4:12)
    at DivisionService.findPeopleByDivision (/Users/dh/Documents/vacation-system-server/dist/src/service/DivisionService.js:21:16)
    at PeopleController.<anonymous> (/Users/dh/Documents/vacation-system-server/dist/src/controller/PeopleController.js:22:78)
    at Generator.next (<anonymous>)
    at /Users/dh/Documents/vacation-system-server/dist/src/controller/PeopleController.js:8:71
    at new Promise (<anonymous>)

## Related code

**seq.ts:**
import { Sequelize } from "sequelize-typescript";
import { MYSQL_CONF } from "../conf/db";

const seq = new Sequelize(MYSQL_CONF);

export default seq;

**sync.ts:**
import seq from "./seq";
seq
  .authenticate()
  .then(() => {
    console.log("auth ok");
  })
  .catch(() => {
    console.log("auth err");
  });
seq.sync({ alter: true }).then(() => {
  console.log("sync ok");
  process.exit();
});

**people.model.ts:**
import {
  Table,
  Column,
  Model,
  BelongsTo,
  ForeignKey,
  HasMany,
} from "sequelize-typescript";
import Division from "./divison.model";
import Record from "./record.model";

@Table({
  timestamps: false,
})
export default class People extends Model {
  @Column({
    allowNull: false,
  })
  name!: string;

  @Column
  catagory!: number;

  @Column
  work_age!: number;

  @ForeignKey(() => Division)
  @Column
  division_id!: number;

  @BelongsTo(() => Division)
  division!: Division;

  @HasMany(() => Record)
  record!: Record[];
}

**PeopleService.ts:**
import seq from "../db/seq";
import { PersonInfoInter } from "../interface/PeopleInterface";
class PeopleService {
  static PeopleService: PeopleService = new PeopleService();
  private People = seq.models.People;
  async findAllPeopleInfo() {
    return await this.People.findAll({
      include: [
        {
          model: seq.models.Record,
          include: [
            {
              model: seq.models.Phase,
            },
          ],
        },
        {
          model: seq.models.Division,
        },
      ],
    });
  }
}

export default PeopleService.PeopleService;

```ts
insert short code snippets here
```

**Comment by nofx3000** [comment]
This is my tsconfig.json:
{
 "compilerOptions": {
 "target": "es2016",  
 "experimentalDecorators": true, 
 "emitDecoratorMetadata": true,
 "module": "commonjs",
 "outDir": "./dist",
 "esModuleInterop": true,
 "forceConsistentCasingInFileNames": true,
 "strict": true,
 "skipLibCheck": true
  }
}
